def guess(txt):
	print("My guess: " + str(txt))

print(True and True)
guess("tru")
print(False and True)
guess("False")
print(1==1 and 2==1)
guess('false')
print("test" == "test")
guess('true')
print(1==1 or 2!=1)
guess('true')
print(True and 1 == 1)
guess('True')
print(False and 0 != 0)
guess('False')
print(True or 1 == 1)
guess('true')
print(1!=0 and 2 == 1)
guess('false')
print("test" != "testing")
guess('true')
print("test" == 1)
guess("false")
print(not(True and False))
guess('true')
print(not(1 == 1 and 0 != 1))
guess('False')
print(not(10 == 1 or 1000 == 1000))
guess('false')
print(not(1 != 10 or 3 == 4))
guess('false')
print(not('testing'=='testing' and 'zed' == 'coolguy'))
guess('true')
print(1==1 and (not("testing"==1 or 1 == 0)))
guess('true')
print("chunky" == "bacon" and (not(3==4 or 3==3)))
guess('false')
print(3==3 and (not("testing"=="testing" or "Python" == "Fun")))
guess('false')
