animals = [ 'bear' , 'python3.6' ,  'peacock', 'kangaroo', 'whale','platypus' ]
print(animals[1])
print("python")
print(animals[2])
print("peacock")
print(animals[0])
print("bear")
print(animals[3])
print("kangaroo")
print(animals[4])
print('whale')
print(animals[2])
print("peackock")
print(animals[5])
print('playtypus')
print(animals[4])
print('whale')
